export default class Strings_Pevneva {
  static FIELD_EMPTY = 'Поле не может быть пустым' 
  static LOGIN_EMPTY = 'Логин не может быть пустым' 
  static LOGIN_EXIST = 'Пользователь с таким логином уже существует' 
  static LOGIN_NOT_EXIST = 'Не существует пользователя с таким логином'  
  static REGISTER_SUCCESS = 'Регистрация прошла успешно!' 
  static REGISTER_FAILED = 'Произошла ошибка во время регистрации' 
  static PASSWORDS_NOT_MATCH = 'Пароли не совпадают'  
  static LOGIN_SUCCESS = 'Вход выполнен успешно' 
  static INCORRECT_PASSWORD = 'Неверный пароль' 
  static NOT_AVALIBLE_CHARACTERS = 'Нельзя использовать этот символ. Можно использовать: '
  static NOW_YOU_CAN_LOGIN = 'Теперь ты можешь войти в свой аккаунт' 
  static ALSO_YOU_CAN_REGISTER_FIRST_PART = 'Еще нету аккаунта? ' 
  static ALSO_YOU_CAN_REGISTER_SECOND_PART = 'Зарегитрируйся!' 
  static ALSO_YOU_CAN_LOGIN_FIRST_PART = 'Уже есть аккаунт? ' 
  static ALSO_YOU_CAN_LOGIN_SECOND_PART = 'Войди!' 
  static HOME_PAGE_TITLE = 'Быстрый и удобный сервис по созднию веб-опросов' 
  static HOME_PAGE_SUBTITLE = 'Создавай опросы в пару кликов!'
  static TRY_NOW = 'Попробовать сейчас'
}